sudo: required
services:
  - docker

script:
  - docker build -t yunus/docker_example_travis .
  - docker images yunus/docker_example_travis

before_deploy:
  - docker login -u 133563  -p 133563Aa?

deploy:
  provider: script
  script: docker push yunus/docker_example_travis
  on:
    branch: master