sudo: required
services:
  - docker

script:
  - docker build -t yunus/docker_example_travis .
  - docker images yunus/docker_example_travis

before_deploy:
  - docker login -u "133563" -p "133563Aa?" docker.io

deploy:
  provider: script
  script: docker push 133563/docker_example_travis
  skip_cleanup: true
  on:
    branch: master