sudo: required
services:
  - docker
script:
  - docker build -t yunus/travis_example_node .
  - docker images yunus/travis_example_node
before_deploy:
  - docker login -u 133563  -p 133563Aa?

deploy:
  provider: script
  script: docker push yunus/travis_example_node
  on:
    branch: master